### ISSUE TITLE
[GitHub Actions] 빌드 수행 중 Setup Ruby 단계에서 실패

### ISSUE THREAD

**Issue by seungriyou** [seungriyou/seungriyou.github.io#5]
## 문제 상황
GitHub Actions 수행 중 <kbd>Setup Ruby</kbd> 단계에서 다음의 문제가 발생하였다.

`google-protobuf` 관련 문제인 것으로 보인다.

<img src="https://github.com/seungriyou/seungriyou.github.io/assets/43572543/cc5c18be-7d77-4aa1-b750-7d931c71c663">

<br>

## 해결 방법
> ref: https://github.com/cotes2020/jekyll-theme-chirpy/issues/1429

`.github/workflows/pages-deploy.yml`의 `ruby-version`을 다음과 같이 수정했다.

관련 커밋: https://github.com/seungriyou/seungriyou.github.io/commit/1d4e9690c9f8bc3cd7767b139f92c48724f88610

```yml
- name: Setup Ruby
    uses: ruby/setup-ruby@v1
    with:
      # (24.01.19 temporal troubleshooting)
      # (https://github.com/cotes2020/jekyll-theme-chirpy/issues/1429#issuecomment-1869460789)
      ruby-version: 3.2.2   # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
      bundler-cache: true
```

<br>

## 메모
임시적인 해결 방법이다. 근원적인 해결 방법을 찾아서 적용해야 한다.

조만간 chirpy theme 업그레이드도 해야할 것 같다.
